version: "3.1"

services:
  db-walle:
    container_name: database-walle
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $PGPASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet-walle
    volumes:
      - ./pgdata:/var/lib/postgresql
    env_file:
      - ".env"

  walle:
    container_name: bot-walle
    build:
      context: .
    command: python app.py
    restart: always
    environment:
      WEBAPP_PORT: 3001
    env_file:
      - ".env"
    depends_on:
      - db-walle
    ports:
      - 8443:3001
    networks:
      - botnet-walle
    volumes:
      - .:/src



networks:
  botnet-walle:
    driver: bridge

